version: '3'
services:
  headout-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: headout-container
    restart: always
    ports:
      - "8080:8080"
    environment:
      NODE_ENV: production
    deploy:
      resources:
        limits:
          memory: 1500M
          cpus: '2'
